### ISSUE TITLE
add .NET 8 Project and Azure Pipelines CI setting

### ISSUE THREAD

**Issue by kkamegawa** [kkamegawa/AzurePipelinesSamples#1]
```[tasklist]
### Tasks
- [x] create .NET 8 ASP⁠.NET Core Project
- [ ] Add Azure Pipelines YAML file
- [ ] Add Test Project
```
